version: "3"
services:
  unturned:
    build: .
    container_name: unturned-server
    ports:
      - "27015:27015/udp"
      - "27016:27016/tcp"
    volumes:
      - ./unturned-data:/unturned
    environment:
      - MAP=pei
      - MODE=normal
      - PLAYERS=16
      - PVE=true
